title = "Example Site For Simple Web Theme"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "simplewebtheme"
themesDir = "./themes"

[params]
headerImage = "https://haoran_mc.gitee.io/ogmc/img/header.svg"

[menu]

[[menu.main]]
title = "wiki"
name = "the wikis"
url = "/ogmc/wiki/index.html"
weight = 1

[[menu.main]]
title = "posts"
name = "all posts"
url = "/ogmc/posts/index.html"
weight = 2

[[menu.main]]
title = "about"
name = "about me"
url = "/ogmc/about/index.html"
weight = 3
